### ISSUE TITLE
Issue creating new Host

### ISSUE THREAD

**Issue by kostas-rs** [imjoey/terraform-provider-ovirt#130]
Hi,

While creating a new host i am encountering the below error:

```
Error: Error applying plan:

1 error(s) occurred:

* ovirt_host.host: 1 error(s) occurred:

2019-05-14T16:33:55.402+0100 [DEBUG] plugin.terraform-provider-ovirt: 2019/05/14 16:33:55 [ERR] plugin: plugin server: accept unix /var/folders/12/f49zv23d5qz6x8wvgzqr2_j00000gn/T/plugin489555894: use of closed network connection
* ovirt_host.host: Fault reason is "Request syntactically incorrect.". Fault detail is "For correct usage, see: https://example.com/ovirt-engine/apidoc#services/hosts/methods/add". HTTP response code is "400". HTTP response message is "400 Bad Request".
```
I am running the below versions of terraform, go and ovirt-engine:

Terraform version: 0.11.13  
Go runtime version: go1.12
ovirt-engine version: 4.3.3.7-1.el7

Below is the snippet of terraform code that i am using:

```
resource "ovirt_host" "host" {
  name = "terraform-host"
  description = "Terraform managed host"
  address = "ovirt-node.example.com"
  root_password = "SomePassword"
  cluster_id = "${ovirt_cluster.cluster.id}"
}
```
Not sure if this is a provider bug or go-ovirt SDK bug but maybe worth having a look.

Thanks!

**Comment by imjoey** [comment]
Hi @kostas-rs , thank you for reporting this. The resource `ovirt_host`  was newly added couple weeks ago, which could be able to pass the acceptance testing along with ovirt-engine 4.1.0. Since currently no enough hardware servers are available, I could hardly do testing and try reproducing the errors. Sorry about that. Could you please provide your `engine.log` file under  `/var/log/ovirt-engine` directory to see if there are any more useful logs?  Thanks.

**Comment by kostas-rs** [comment]
Hey @imjoey, thank you for the quick reply and suggestion. This helped me diagnose the issue. 

For reference, please see the error in the engine.log file:

```
2019-05-15 09:08:43,403+01 ERROR [org.ovirt.engine.api.restapi.resource.validation.IOExceptionMapper] (default task-1) [] IO exception while processing "POST" request for path "/h
osts"
2019-05-15 09:08:43,403+01 ERROR [org.ovirt.engine.api.restapi.resource.validation.IOExceptionMapper] (default task-1) [] Exception: java.io.IOException: javax.xml.stream.XMLStrea
mException: ParseError at [row,col]:[1,226]
Message: The entity name must immediately follow the '&' in the entity reference.
        at org.ovirt.engine.api.restapi.xml.JAXBProvider.readFrom(JAXBProvider.java:195) [restapi-jaxrs.jar:]
        at org.ovirt.engine.api.restapi.xml.JAXBProvider.readFrom(JAXBProvider.java:161) [restapi-jaxrs.jar:]
      .
      .
      .
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,226]
Message: The entity name must immediately follow the '&' in the entity reference.
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604) [rt.jar:1.8.0_212]
        at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:196)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:386)
        at org.ovirt.engine.api.restapi.xml.JAXBProvider.readFrom(JAXBProvider.java:183) [restapi-jaxrs.jar:]
        ... 114 more
```

The issue was with the password which contained a literal "&" character in the end. I am guessing this is an issue because of the way XML gets parsed in the engine. Removing the "&" character resolved the issue. Again thank you for your reply!

**Comment by imjoey** [comment]
Hi @kostas-rs , good to see the problem has been resolved. Thanks again for your feedback.
